server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    driver-class-name: ${sky.datasource.driver-class-name}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qrs.entity
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


logging:
  level:
    com:
      qrs:
        mapper: debug
        service: info
        controller: info


sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: JWT-key-qrs-"!_BVdwDc@?=77‘ZUwk-g%^di-ope][#-
    # 设置jwt过期时间
    admin-ttl: 86400000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}